version: '3.9'

services:
  api:
    image: skitskni/api:latest
    depends_on: 
      - db
    ports:
      - '5000:80'
    env_file:
      - .env
        
  db:
    image: postgres
    ports:
      - '6000:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    depends_on:
      - minio
        
  minio:
    image: minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${S3Service__AccessKey}
      - MINIO_ROOT_PASSWORD=${S3Service__SecretKey}
    command: server --console-address ":9001" --address ":9000" /data

volumes:
  minio_data:
    driver: local
  postgres-data: