version: '3.9'

services:
  api:
    image: skit
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - db
    ports:
      - 5000:80
        
  db:
    image: postgres
    ports:
      - 6000:5432
    environment: 
      POSTGRES_DB: skit-database
      POSTGRES_USER: skit-user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
volumes:
  postgres-data: